# Generated by Django 3.2.15 on 2022-10-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='id_origen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporada',
            name='num_capitulos',
            field=models.IntegerField(default=0),
        ),
    ]
